[package]
name = "what_is_my_ip"
version = "0.1.0"
authors = ["nell"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pnet = "0.22.0"
dns-lookup = "1.0.1"